## **Import the TensorFlow library**

This code contains a small script that is used for generating a folder full of images. The idea is to show these images to the OpenMV camera when the training with the OL methos is required. Since the idea is to apply a supervised training is required to have a ground truth forthe computation of the error that the model is doing. This script fills a directory with images of digits and creates a txt file in which all the labels are saved. 

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Dropout, Dense, Flatten, Reshape
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras import backend as K
from tensorflow.keras import optimizers

import matplotlib.pyplot as plt 
import matplotlib.image as mpimg
from PIL import Image

import numpy as np
import pandas as pd
import seaborn as sns
import random 
import csv 
import sys
import os
import re
from random import seed

import time
#import os, os.path
import cv2
import glob
from keras import applications
#from keras.applications import vgg19
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, f1_score

from numpy.ma.core import size

import torchvision.models as models
from torchvision import transforms
ROOT_PATH = os.path.abspath('')
sys.path.insert(0, ROOT_PATH + '/lib')

# VS Code

# IMPORT AND LOAD MODELS

In [1]:
import tensorflow as tf
from tensorflow import keras

import time

import sys
import numpy as np
import matplotlib.pyplot as plt

# Absolute path is needed to load libraries 
ROOT_PATH = os.path.abspath('')
sys.path.append(ROOT_PATH + '/lib')

# from lib.Kmeans_lib import *
# from lib.EvalMetrics import *
# 
from lib.CustomLayer_lib import Custom_Layer
from lib.utils import *

# from lib.Kmeans_lib import 


2022-11-03 13:27:31.105319: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


# TRAIN THE MODEL ON THE DIGITS 6-9 (OL METHOD)

In [2]:
# Options

# Load model and features
n_feat = 10 # Select number of features
MODEL_PATH = 'Models/{}/'.format(n_feat)
features_saved = np.loadtxt(MODEL_PATH + 'll_features.txt')
labels_features_saved = np.loadtxt(MODEL_PATH + 'll_labels_features.txt').astype(int)
model = keras.models.load_model(MODEL_PATH + 'original_mnist_cnn.h5') # Original model 

# Settings 
settings_train = TrainSettings()
settings_train.verbosity = 'NONE'
settings_train.clustering_labels = list(range(0, 10))
settings_train.fill_cmtx = False
#settings_train.save_output = False
#settings_train.save_plots = False
settings_train.mode = 'Train'

settings_test = TrainSettings()
settings_test.verbosity = 'DEBUG'
settings_test.clustering_labels = list(range(0, 10))
settings_test.fill_cmtx = True
#settings_test.save_output = True
#settings_test.save_plots = True
settings_test.mode = 'Test'


2022-11-02 16:37:09.542564: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# Create datasets
n_train = 1000
n_test = 500
digits_train, label_digits_train, digits_test, label_digits_test = create_dataset(n_train, n_test)

# Define model
Model = Custom_Layer(model)
Model.title      = 'OL'
Model.filename   = 'OL'
Model.l_rate     = 0.01
Model.update_batch_size = 8
Model.ll_method = 'OL'

# Clustering batch dize
Model.clustering_batch_size = 50

Model.settings = settings_train
RunOneEpoch(Model, digits_train, label_digits_train,features_saved, labels_features_saved)

Model.settings = settings_test
RunOneEpoch(Model, digits_test, label_digits_test,features_saved, labels_features_saved)

Starting Train batch: 1/20
New digit detected -> 6
New digit detected -> 9
New digit detected -> 8
New digit detected -> 7
Starting Train batch: 2/20
Starting Train batch: 3/20
Starting Train batch: 4/20
Starting Train batch: 5/20
Starting Train batch: 6/20
Starting Train batch: 7/20
Starting Train batch: 8/20
Starting Train batch: 9/20
Starting Train batch: 10/20
Starting Train batch: 11/20
Starting Train batch: 12/20
Starting Train batch: 13/20
Starting Train batch: 14/20
Starting Train batch: 15/20
Starting Train batch: 16/20
Starting Train batch: 17/20
Starting Train batch: 18/20
Starting Train batch: 19/20
Starting Train batch: 20/20
Starting Test batch: 1/10
Fitting 150 samples in 10 clusters took 0.6882100105285645 seconds
[[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.  0.  5.  2.  0.]
 [ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.  0.  0.  0.  1.  7.]
 [

/Users/andrea/Documents/VS Code/MachineLearning/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/andrea/Documents/VS Code/MachineLearning/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Fitting 150 samples in 10 clusters took 0.6613941192626953 seconds
[[ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  1.  8.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [ 0.  0.  9.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  0.  0.  6.  0.  1.]]
Argmax: [7 1 4 0 8 2 3 9 5 6]
Cluster to label map:  {0: 7, 1: 1, 2: 4, 3: 0, 4: 8, 5: 2, 6: 3, 7: 9, 8: 5, 9: 6}
Clustering metrics

Silhouette Precision: 0.14
Calinks-Harabasz Recall: 9.73
Davies-Bouldin -score: 2.07

Clusters inertia: 37693.92

Confusion Matrix

[[4 0 0 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0 0 0]
 [0 0 9 0 0 0 0 1 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 1]
 [0 0 0 0 0 8 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 5]]

Accu

/Users/andrea/Documents/VS Code/MachineLearning/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/andrea/Documents/VS Code/MachineLearning/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Starting Test batch: 5/10
Fitting 150 samples in 10 clusters took 0.7814309597015381 seconds
[[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  1.  0.  1.  0.  0.  0.  5.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  9.  0.]
 [ 8.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]
 [ 1.  0.  0.  1.  0.  4.  0.  4.  0.  0.]]
Argmax: [4 6 1 7 0 8 5 9 3 2]
Cluster to label map:  {0: 4, 1: 6, 2: 1, 3: 7, 4: 0, 5: 8, 6: 5, 7: 9, 8: 3, 9: 2}
Clustering metrics

Silhouette Precision: 0.15
Calinks-Harabasz Recall: 9.91
Davies-Bouldin -score: 2.01

Clusters inertia: 36755.52

Confusion Matrix

[[7 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 7 0 0 0 0]
 [0 1 0 0 0 0 6 0 1 0]
 [0 1 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 6 0]
 [0

/Users/andrea/Documents/VS Code/MachineLearning/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/andrea/Documents/VS Code/MachineLearning/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Starting Test batch: 8/10
Fitting 150 samples in 10 clusters took 0.6581501960754395 seconds
[[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  3.  0.  0.  1.  0.  0.  0.  0.  5.]
 [ 0.  0.  0.  9.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  4.  0.  0.  0.  0.  6.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  9.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  8.  0.]
 [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  7.  0.  0.  0.  0.  2.  0.  0.]]
Argmax: [8 1 9 3 7 0 5 4 6 2]
Cluster to label map:  {0: 8, 1: 1, 2: 9, 3: 3, 4: 7, 5: 0, 6: 5, 7: 4, 8: 6, 9: 2}
Clustering metrics

Silhouette Precision: 0.14
Calinks-Harabasz Recall: 9.34
Davies-Bouldin -score: 2.10

Clusters inertia: 37762.58

Confusion Matrix

[[5 0 0 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 3 5 0 0 0 0 0 0]
 [0 1 0 0 3 0 0 0 0 3]
 [0 1 1 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 4 0 0]
 [0 0 0 1 0 0 0 0 5 0]
 [0

In [4]:
# Evaluation metrics
from lib.simulation_lib import * 

plot_barChart(Model)
plot_confMatrix(Model)
plot_table(Model)

NameError: name 'plot_barChart' is not defined